name : hola-mundo
on: [push]
jobs:
    hola-mundo:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
          
          - name: Setup Dart
            uses: dart-lang/setup-dart@v1
  
          - name: Hello from Dart
            run: dart hello-world.dart